/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/gaoxiao-2025': RouteRecordInfo<
      '/posts/gaoxiao-2025',
      '/posts/gaoxiao-2025',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/greatwall-5': RouteRecordInfo<
      '/posts/greatwall-5',
      '/posts/greatwall-5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pangushi-da': RouteRecordInfo<
      '/posts/pangushi-da',
      '/posts/pangushi-da',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pengcheng-2025': RouteRecordInfo<
      '/posts/pengcheng-2025',
      '/posts/pengcheng-2025',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pwn-basics': RouteRecordInfo<
      '/posts/pwn-basics',
      '/posts/pwn-basics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/shanghai-2025': RouteRecordInfo<
      '/posts/shanghai-2025',
      '/posts/shanghai-2025',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/usb-keyboard-traffic': RouteRecordInfo<
      '/posts/usb-keyboard-traffic',
      '/posts/usb-keyboard-traffic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/wanqubei-2025': RouteRecordInfo<
      '/posts/wanqubei-2025',
      '/posts/wanqubei-2025',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/wanqubei-2026': RouteRecordInfo<
      '/posts/wanqubei-2026',
      '/posts/wanqubei-2026',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ycb-2025': RouteRecordInfo<
      '/posts/ycb-2025',
      '/posts/ycb-2025',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.9_10aa341a06906d97b82887c3d5c30560/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@1.0.0-rc.9_@babel+pa_dc331101b055db863826d110f97d2ece/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.9_10aa341a06906d97b82887c3d5c30560/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.9_10aa341a06906d97b82887c3d5c30560/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/gaoxiao-2025.md': {
      routes:
        | '/posts/gaoxiao-2025'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/greatwall-5.md': {
      routes:
        | '/posts/greatwall-5'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pangushi-da.md': {
      routes:
        | '/posts/pangushi-da'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pengcheng-2025.md': {
      routes:
        | '/posts/pengcheng-2025'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pwn-basics.md': {
      routes:
        | '/posts/pwn-basics'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/shanghai-2025.md': {
      routes:
        | '/posts/shanghai-2025'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/usb-keyboard-traffic.md': {
      routes:
        | '/posts/usb-keyboard-traffic'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/wanqubei-2025.md': {
      routes:
        | '/posts/wanqubei-2025'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/wanqubei-2026.md': {
      routes:
        | '/posts/wanqubei-2026'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/ycb-2025.md': {
      routes:
        | '/posts/ycb-2025'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
